# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.
 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"


#one approch can be use hashmap create a hashmap  another can be check oocurence of each char in t 


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        each char in string associated with a assci which  will be integer 
        string t will always have more chars than string s and just one char extra 
        we can just loop over all char in strings s do xor of all chars in s 
        Loop Over all chars in t and add xor to result remaining one will be unique char 
        """
        res = 0
        for c in s:
            res ^= ord(c)
        for c in t:
            res ^= ord(c)
        return chr(res)


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        similer as above for each char there will be assci 
        subtract assci of each char in s from result 
        add assci for each char in t to result 
        remaining one will be 
        """
        res = 0
        for c in s:
            res -= ord(c)
        for c in t:
            res += ord(c)
        return chr(res)